# Generated by Django 4.2.11 on 2025-09-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='complete_status',
            field=models.BooleanField(default=False),
        ),
    ]
